sudo: required
services:
  - docker
before_install:
  - docker build -t bobthebuilder24/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true bobthebuilder24/react-test npm test

after_success:
  - docker build -t bobthebuilder24/multi-client ./client
  - docker build -t bobthebuilder24/multi-server ./server
  - docker build -t bobthebuilder24/multi-worker ./worker
  - docker build -t bobthebuilder24/multi-nginx ./nginx
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take above images and push to docker hub
  - docker push bobthebuilder24/multi-client
  - docker push bobthebuilder24/multi-server
  - docker push bobthebuilder24/multi-worker
  - docker push bobthebuilder24/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-421863480159'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY